```

#########By PATH
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /wear
        pathType: Prefix
        backend:
          serviceName: wear-service
          servicePort: 80
      - path: /watch
        pathType: Prefix
        backend:
          serviceName: watch-service
          servicePort: 80

    
```

```
##########By Domain
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-fanout-example
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: service1
          servicePort: 4200
      - path: /bar
        backend:
          serviceName: service2
          servicePort: 8080
 - host: watch.bar.com
   http:
     paths:
     - path: /foo
       backend:
         serviceName: service1
         servicePort: 4200
     - path: /bar
       backend:
         serviceName: service2
         servicePort: 8080          
```